[package]
name = "cxtweaker"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clang = { version = "2.0.0", features = ["clang_10_0"] }
clap = { version = "4.0.32", features = ["derive", "color"] }
colored = "2.1.0"
indicatif = "0.17.7"